### ISSUE TITLE
Simplify portfolio pipeline on project page

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#29]
<img width="1105" alt="screen shot 2018-10-02 at 16 43 16" src="https://user-images.githubusercontent.com/42815657/46375759-4dd99580-c662-11e8-8e0e-bf93442a7ebb.png">
^ The current solution on project pages doesn't quite eliminate that instinct to hover over the pipeline.

<img width="637" alt="screen shot 2018-10-02 at 2 53 11 pm" src="https://user-images.githubusercontent.com/42815657/46375642-f6d3c080-c661-11e8-819a-173c23ed628a.png">
^ This is just a suggestion of what we're thinking - by no means prescriptive.

**Comment by jennyvanderheiden** [comment]
@abandea - We are proposing changing the look of the phase designation on the individual project pages to be clearer. 

- we still think it is informative to indicate visually and in a connected way to the portfolio visualizer. So slightly modifying the look with the bold indicator arrow underneath does a good job there. 

- we don't recommend removing the sub-categories because the arrow will be specifically pointing at a phase and without that being listed, it looks a bit arbitrary and unconnected to the phase indicator elsewhere. But understand your concern with it looking clickable. 

Indicator for active: https://gyazo.com/61994e3ab321e4a5d7003b2c724931f8
Indicator for graduated: https://gyazo.com/535dcc2809faac54f463f81776b1b9fa

**Comment by jennyvanderheiden** [comment]
Furthermore, we think it may be a good idea to add a note next to the project title with graduated or discontinued to further indicate.
https://gyazo.com/8a41345f3f250e59758b9e92be389a67

**Comment by tbeck** [comment]
@abandea, @jennyvanderheiden  - These changes are in place on the staging site for review.

**Comment by jennyvanderheiden** [comment]
@tbeck @abandea I think this looks good!
