### ISSUE TITLE
milestones dates + hyperlinks

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#9]
Hello! 

I've begun inserting project data on cloud cannon and noticed a couple of things for project "milestones."

1) Is there a way to show the date as "month/year" or even a date range (e.g. May - July 2018). Very rarely will we have data like time or even day. 

Not totally necessary, but nice to have: 
2) Is there an easy way to hyperlink the entire milestone or the title of the milestone, rather than within the description itself. We did it in a way that each milestone is connected to one document or link. 

Thanks!

**Comment by tbeck** [comment]
Hi @abandea !

1) In the design we are only using the month/year, but by forcing a date type on the field we have the ability to standardize the formatting in the template rather than the point of data entry. You can enter in any "day" or "time" and it should not have an effect.

That being said... we are not accounting for the possibility of a "range". Do you think this is something we should take into consideration? We could adjust this to be a text field? Then you could enter in any string. ie... March, 2019 **or** May - July 2018. 

2) Absolutely... we can update the configuration so that this does not need to be included in the description. 

Let me know if we should make updates to the project model (date) field?

Thanks!
T

**Comment by abandea** [comment]
hey @tbeck 

1. Okay awesome! And as for range, that could be something to consider in V2, but for now it's okay as is

2. thanks, that'll be helpful!

**Comment by tbeck** [comment]
commit: 856dcc4
